### ISSUE TITLE
Devices become unavailable after HA restart

### ISSUE THREAD

**Issue by southwestflavorz** [Arbuzov/hass-broadlink-ac-mqtt#4]
When I restart HA, the devices become unavailable. The only way to get them back working is to restart the add-on.

**Comment by rumunn95** [comment]
same issue

**Comment by southwestflavorz** [comment]
I'm bypassing the issue for now by writing an automation that restarts the addon 30 seconds after HA starts.

**Comment by rumunn95** [comment]
> I'm bypassing the issue for now by writing an automation that restarts the addon 30 seconds after HA starts.

Can you share your automation?

**Comment by southwestflavorz** [comment]
Of course, basically the automation waits 30 seconds after home assistant starts up, then it restarts the add-on. With this method, I haven't had an issue with devices becoming unavailable.

alias: Automation - Restart Aircon Add-on At Startup
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: hassio.addon_restart
    data:
      addon: e9fb2284_broadlink-ac-mqtt
mode: single

**Comment by Arbuzov** [comment]
Actually I restart it more frequently cause there are some issues at the original source codes:
```
alias: Air driver restart
description: ""
trigger:
  - platform: time_pattern
    minutes: "1"
condition: []
action:
  - service: hassio.addon_restart
    data:
      addon: e9fb2284_broadlink-ac-mqtt
mode: single
```
